# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17ySJAiZ6dzhdY7fgSiJfQQ4qjxTEeR2j
"""

def print_board(board):
    """Prints the current state of the game board."""
    print("\n")
    print(f" {board[0]} | {board[1]} | {board[2]} ")
    print("---|---|---")
    print(f" {board[3]} | {board[4]} | {board[5]} ")
    print("---|---|---")
    print(f" {board[6]} | {board[7]} | {board[8]} ")
    print("\n")

def check_winner(board, player):
    """Checks if the specified player has won the game."""
    win_conditions = [
        [0, 1, 2], [3, 4, 5], [6, 7, 8],
        [0, 3, 6], [1, 4, 7], [2, 5, 8],
        [0, 4, 8], [2, 4, 6]
    ]
    for condition in win_conditions:
        if board[condition[0]] == board[condition[1]] == board[condition[2]] == player:
            return True
    return False

def is_board_full(board):
    """Returns True if all spaces are occupied, meaning a draw."""
    return all(space in ['X', 'O'] for space in board)

def play_game():
    """Main function to run the Tic-Tac-Toe game logic."""

    board = [str(i) for i in range(1, 10)]
    current_player = "X"

    print("--- Welcome to Python Tic-Tac-Toe! ---")

    while True:
        print_board(board)


        try:
            choice = int(input(f"Player {current_player}, choose a spot (1-9): "))
            position = choice - 1

            if choice < 1 or choice > 9:
                print("Invalid input! Please choose a number between 1 and 9.")
                continue
            if board[position] in ['X', 'O']:
                print("That spot is already taken! Try another one.")
                continue
        except ValueError:
            print("Invalid input! Please enter a valid number.")
            continue


        board[position] = current_player


        if check_winner(board, current_player):
            print_board(board)
            print(f" Congratulations! Player {current_player} wins! ")
            break


        if is_board_full(board):
            print_board(board)
            print(" It's a draw!")
            break


        current_player = "O" if current_player == "X" else "X"

if __name__ == "__main__":
    play_game()
print("Sambriddhi Prasai , 1BF24CS268")